[package]
name = "rust-music-theory"
version = "0.1.0"
authors = ["Ozan Kasikci <ozan@kasikci.io>"]
edition = "2018"

[dependencies]
strum = "0.17.1"
strum_macros = "0.17.1"
regex = "1"
clap = "2.31"
