[package]
name = "fantasy-in-rust"
version = "0.1.0"
authors = ["Ozan Kasikci <ozan@kasikci.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
